2025-09-10 18:36:57 UTC
Windows-11-10.0.22631-SP0
Ren'Py 8.4.1.25072401

Early init took 82 ms
Loading error handling took 33 ms
<unknown>:1: SyntaxWarning: invalid escape sequence '\ '
<unknown>:1: SyntaxWarning: invalid escape sequence '\ '
Loading script took 440 ms
Loading save slot metadata took 46 ms
Loading persistent took 0 ms
Running init code took 82 ms
Loading analysis data took 12 ms
Analyze and compile ATL took 3 ms
Reloading save slot metadata took 31 ms
Backing up script files to 'C:\\Users\\nicole\\AppData\\Roaming/RenPy/backups\\Inkbound':
Dump and make backups took 81 ms
Cleaning cache took 0 ms
Making clean stores took 0 ms
Initial gc took 61 ms
DPI scale factor: 1.500000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: b"Couldn't load nvlib." (can be ignored)
Creating interface object took 2 ms
Init translation took 0 ms
Cleaning stores took 0 ms
Load screen analysis took 1 ms
Analyze screens took 17 ms
Save screen analysis took 17 ms
Save pyanalysis took 7 ms
Save bytecode took 35 ms
Running _start took 2 ms
Interface start took 369 ms

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: 'ATI Technologies Inc.'
Renderer: 'AMD Radeon(TM) Graphics'
Version: '4.6.0 Compatibility Profile Context 22.20.44.59.230413'
Display Info: <Info({'bitsize': 32, 'bytesize': 4, 'masks': (16711680, 65280, 255, 0), 'shifts': (16, 8, 0, 0), 'losses': (0, 0, 0, 8), 'current_w': 1920, 'current_h': 1080, 'refresh_rate': 60, 'hw': False, 'wm': True, 'video_mem': 268435456, 'blit_hw': False, 'blit_hw_CC': False, 'blit_hw_A': False, 'blit_sw': False, 'blit_sw_CC': False, 'blit_sw_A': False})>
Screen sizes: virtual=(1920, 1080) physical=(1920, 1046) drawable=(1920, 1046)
Maximum texture size: 4096x4096
Screen sizes: virtual=(1920, 1080) physical=(1920, 1046) drawable=(1920, 1046)
Maximum texture size: 4096x4096
Cleaning stores took 0 ms
Load screen analysis took 35 ms
Analyze screens took 0 ms
Running _start took 6 ms

Full traceback:
  File "renpy/main.py", line 614, in main
    run(restart)
    ~~~^^^^^^^^^
  File "renpy/main.py", line 137, in run
    renpy.execution.run_context(True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "renpy/execution.py", line 1022, in run_context
    context.run()
    ~~~~~~~~~~~^^
  File "renpy/common/00start.rpy", line 282, in script
    python:
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/common/00start.rpy", line 284, in <module>
    renpy.call_in_new_context(_restart[2])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "renpy/game.py", line 372, in call_in_new_context
    return renpy.execution.run_context(False)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "renpy/execution.py", line 1022, in run_context
    context.run()
    ~~~~~~~~~~~^^
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
    ~~~~~~~~~~~^^
  File "renpy/ui.py", line 304, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/core.py", line 2219, in interact
    repeat, rv = self.interact_core(
                 ~~~~~~~~~~~~~~~~~~^
        preloads=preloads,
        ^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )  # type: ignore
    ^                
  File "renpy/display/core.py", line 3137, in interact_core
    self.quit_event()
    ~~~~~~~~~~~~~~~^^
  File "renpy/display/core.py", line 1813, in quit_event
    renpy.display.behavior.run(renpy.config.quit_action)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/behavior.py", line 411, in run
    return action(*args, **kwargs)
           ~~~~~~^^^^^^^^^^^^^^^^^
  File "renpy/common/00action_menu.rpy", line 274, in __call__
    renpy.quit(save=True)
    ~~~~~~~~~~^^^^^^^^^^^
  File "renpy/exports/restartexports.py", line 133, in quit
    raise renpy.game.QuitException(relaunch=relaunch, status=status)
renpy.game.QuitException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "renpy/bootstrap.py", line 376, in bootstrap
    renpy.main.main()
    ~~~~~~~~~~~~~~~^^
  File "renpy/main.py", line 626, in main
    renpy.persistent.update(True)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "renpy/persistent.py", line 461, in update
    save()
    ~~~~^^
  File "renpy/persistent.py", line 484, in save
    renpy.loadsave.location.save_persistent(compressed)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "renpy/savelocation.py", line 619, in save_persistent
    l.save_persistent(data)
    ~~~~~~~~~~~~~~~~~^^^^^^
  File "renpy/savelocation.py", line 431, in save_persistent
    safe_rename(fn_new, fn)
    ~~~~~~~~~~~^^^^^^^^^^^^
  File "renpy/loadsave.py", line 60, in safe_rename
    os.unlink(new)
    ~~~~~~~~~^^^^^
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\nicole\\AppData\\Roaming/RenPy/Inkbound-1755786600/sync\\persistent'

While running game code:
renpy.game.QuitException

During handling of the above exception, another exception occurred:

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\nicole\\AppData\\Roaming/RenPy/Inkbound-1755786600/sync\\persistent'
