I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 98, in script
    $ name
  File "game/script.rpy", line 98, in <module>
    $ name
      ^^^^
NameError: name 'name' is not defined

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/script.rpy", line 98, in script
    $ name
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "game/script.rpy", line 98, in <module>
    $ name
      ^^^^
NameError: name 'name' is not defined

Windows-11-10.0.22631-SP0 AMD64
Ren'Py 8.4.1.25072401
Inkbound 1.0
Tue Sep  9 16:24:31 2025
